### ISSUE TITLE
Not able to add funds

### ISSUE THREAD

**Issue by Skerpiio** [TON-Time/project#1]
For some reason the app will not take from my wallet

**Comment by Darrellben** [comment]
Hey there @Skerpiio !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **TON7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Ton coin Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.
